---
- name: Configure Environment
  hosts: all
  become: yes
  vars:
    image: ""

  tasks:
    - name: Pull application Docker image
      community.docker.docker_image:
        name: "{{ image }}"
        source: pull

    - name: Stop existing container (if running)
      community.docker.docker_container:
        name: app_container
        state: absent
        force_kill: true

    - name: Run application container
      community.docker.docker_container:
        name: app_container
        image: "{{ image }}"
        state: started
        restart_policy: always
        published_ports:
          - "8080:8080"
