# Use a base image with Java runtime
FROM openjdk:17-jdk-slim

# Set the working directory inside the container
WORKDIR /healthcare_project

# Copy the jar file to the container
COPY target/account-microservice-0.0.1-SNAPSHOT.jar healthcare_project.jar

# Expose the application port
EXPOSE 8080

# Run the application
ENTRYPOINT ["java", "-jar", "healthcare_project.jar"]
