apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app
  labels:
    app: healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
        - name: healthcare-container
          image: {{IMAGE_TAG}}  # Placeholder replaced by Jenkins
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  selector:
    app: healthcare
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
